### ISSUE TITLE
Example doesn't compile in Arduino IDE 1.6.8

### ISSUE THREAD

**Issue by gittyhubbyfrankybobby** [Orange-Cat/MenuBackend#1]
Opened the hellomenu example and get these errors when compiling.
I'm not smart enough yet to fix it.

Build options changed, rebuilding all
HelloMenu:17: error: 'menuUseEvent' was not declared in this scope

 MenuBackend menu = MenuBackend(menuUseEvent,menuChangeEvent);

```
                            ^
```

HelloMenu:17: error: 'menuChangeEvent' was not declared in this scope

 MenuBackend menu = MenuBackend(menuUseEvent,menuChangeEvent);

```
                                         ^
```

Multiple libraries were found for "MenuBackend.h"
 Used: C:\Users\DAwesome\Documents\Arduino\libraries\MenuBackend-master
 Not used: C:\Users\DAwesome\Documents\Arduino\libraries\menubackend2
exit status 1
'menuUseEvent' was not declared in this scope

**Comment by techfixpros** [comment]
Please see [http://uecide.org/forum/viewtopic.php?f=14&t=284](url)

Add the following before `MenuBackend(menuUseEvent,menuChangeEvent);`

`void menuChangeEvent(MenuChangeEvent changed);`
`void menuUseEvent(MenuUseEvent used);`

**Comment by colliebudz** [comment]
i had the same issue of not compiling on arduine ide 1.8.9
had to change Strings.h to strings.h in the MenuBackend.h
